//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrawingManagerDll {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class IFCEXPORTSETTINGS : global::System.Configuration.ApplicationSettingsBase {
        
        private static IFCEXPORTSETTINGS defaultInstance = ((IFCEXPORTSETTINGS)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new IFCEXPORTSETTINGS())));
        
        public static IFCEXPORTSETTINGS Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\IFCEXPORT\\Projects\r\n")]
        public string STOREDPROJECTS {
            get {
                return ((string)(this["STOREDPROJECTS"]));
            }
            set {
                this["STOREDPROJECTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MH2")]
        public string SelectedProject {
            get {
                return ((string)(this["SelectedProject"]));
            }
            set {
                this["SelectedProject"] = value;
            }
        }
    }
}
